# 1. Identificacion y puerto 8082
spring.application.name=catalog-service
server.port=8082

# 2. Conexion MongoDB NoSQL
spring.data.mongodb.uri=mongodb://localhost:27017/gamestore_catalog

# 3. Eureka Client
eureka.client.enabled=true
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
spring.cloud.config.enabled=false